# Generated by Django 6.0.6 on 2026-06-07 12:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saccos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_code', models.CharField(max_length=20, unique=True)),
                ('route_name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('route_type', models.CharField(choices=[('EXPRESS', 'Express'), ('NORMAL', 'Normal'), ('INTER_COUNTY', 'Inter-County')], default='NORMAL', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_duration', models.DurationField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='saccos.sacco')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('distance_from_origin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare_from_origin', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_pickup', models.BooleanField(default=True)),
                ('is_dropoff', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
            ],
            options={
                'db_table': 'stops',
                'ordering': ['route', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['sacco', 'status'], name='routes_sacco_i_00ac94_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination'], name='routes_origin_4cde7f_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_code'], name='routes_route_c_b515e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('route', 'order')},
        ),
    ]
