# Generated by Django 6.0.6 on 2026-06-07 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('saccos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Bus'), ('MINIBUS', 'Minibus'), ('VAN', 'Van')], max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_MAINTENANCE', 'In Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='ACTIVE', max_length=20)),
                ('insurance_expiry', models.DateField()),
                ('road_worthiness_expiry', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='drivers.driver')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='saccos.sacco')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('WHEELCHAIR', 'Wheelchair')], default='REGULAR', max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('row', models.IntegerField()),
                ('column', models.CharField(max_length=1)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'seats',
                'ordering': ['floor', 'row', 'column'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['sacco', 'status'], name='vehicles_sacco_i_610938_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('vehicle', 'seat_number')},
        ),
    ]
