# Generated by Django 6.0.6 on 2026-06-07 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductors', '0001_initial'),
        ('drivers', '0001_initial'),
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DELAYED', 'Delayed')], default='SCHEDULED', max_length=20)),
                ('day_of_week', models.CharField(max_length=3)),
                ('is_recurring', models.BooleanField(default=False)),
                ('available_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField(default=0)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='conductors.conductor')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='drivers.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='routes.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'schedules',
                'indexes': [models.Index(fields=['route', 'departure_time'], name='schedules_route_i_4aa245_idx'), models.Index(fields=['vehicle', 'departure_time'], name='schedules_vehicle_d27d41_idx'), models.Index(fields=['status', 'departure_time'], name='schedules_status_967139_idx')],
            },
        ),
    ]
